
include:
  - project: "workingmouse/devops/gitlab-pipelines"
    ref: "feature/2.0"
    file: "/package/docker.yml"

stages:
  - test
  - package

variables:
    DISABLE_PACKAGE: "true"

test-tools:
  image: registry.workingmouse.com.au/workingmouse/projects/internal/tools:latest
  stage: test
  rules:
    - when: always
  script:
    - export TOOLS=. && source tools.sh && source _test.sh

package-tools:
  extends:
    - .package:docker
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

package-bw:
  extends:
    - package-tools
  variables:
    DOCKER_CONTEXT: ./services/bitwarden/
    CONTAINER_IMAGE_PATH: /bw
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - services/bitwarden/*
        - .gitlab-ci.yml

package-mattermost-message-scheduler:
  extends:
    - package-tools
  variables:
    DOCKER_CONTEXT: ./services/mattermost/message-scheduler/
    CONTAINER_IMAGE_PATH: /mattermost.message-scheduler
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - services/mattermost/message-scheduler/*
        - .gitlab-ci.yml
