
include:
  - project: "workingmouse/devops/gitlab-pipelines"
    ref: "feature/2.0"
    file: "/package/docker.yml"

stages:
  - test
  - package

test-tools:
  image: registry.workingmouse.com.au/workingmouse/projects/internal/tools:latest
  stage: test
  rules:
    - when: always
  script:
    - export TOOLS=. && source tools.sh && source _test.sh

package:docker:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  variables:
    IMAGE_TAG: latest

package-bw:
  extends:
    - package:docker
  variables:
    DOCKER_CONTEXT: ./services/bitwarden/
    IMAGE_SUBPATH: bw
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - services/bitwarden/*
        - .gitlab-ci.yml

package-mattermost-message-scheduler:
  extends:
    - package:docker
  variables:
    DOCKER_CONTEXT: ./services/mattermost/message-scheduler/
    IMAGE_SUBPATH: mattermost.message-scheduler
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - services/mattermost/message-scheduler/*
        - .gitlab-ci.yml
