
include:
  - project: "workingmouse/devops/gitlab-pipelines"
    ref: "1.7.3.1"
    file: "/shared/core/package-docker.yml"

stages:
  - test
  - package

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

variables:
    DISABLE_PACKAGE: "true"

test:
  stage: test
  rules:
    - when: always
  script:
    - export TOOLS=. && source tools.sh && source _test.sh

package-tools:
  extends:
    - .package-docker

package-bw:
  extends:
    - .package-docker
  variables:
    DOCKER_CONTEXT: ./services/bitwarden/
    CONTAINER_IMAGE_PATH: /bw
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - services/bitwarden/*
        - .gitlab-ci.yml

package-mattermost-message-scheduler:
  extends:
    - .package-docker
  variables:
    DOCKER_CONTEXT: ./services/mattermost/message-scheduler/
    CONTAINER_IMAGE_PATH: /mattermost.message-scheduler
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - services/mattermost/message-scheduler/*
        - .gitlab-ci.yml
